apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loan-prediction
  template:
    metadata:
      labels:
        app: loan-prediction
    spec:
      containers:
      - name: loan-app-container
        image: bitech20/loan-approval-prediction-model:v1
        ports:
        - containerPort: 8501
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"